<li id="cmt2">
            <div class="cmt-info">
              <div class="gravatar"> <img alt="[field:name/]" src="/style/images/0.png" class="avatar avatar-45 photo" height="45" width="45"> </div>
              <div class="cmt-author"> <a href="[field:arcurl/]" rel="nofollow" target="_blank">[field:name/]</a> </div>
            </div>
            <div class="cmt-con">[field:cont/]
            </div>
          </li>
        </ol>