<?php
$z[0]=Array("global","",139,165);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",206,232);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("type","<li id=\"navbar-category-1\"><a href=\"[field:typelink /]\"><i class=\"icon-tasks\"></i> [field:typename /]</a></li>",441,585);
$z[2][4]=array();
$z[2][4]['typeid']="1";
$z[3]=Array("type","<li id=\"navbar-category-1\"><a href=\"[field:typelink /]\"><i class=\"icon-share\"></i> [field:typename /]</a></li>",599,743);
$z[3][4]=array();
$z[3][4]['typeid']="2";
$z[4]=Array("type","<li id=\"navbar-category-1\"><a href=\"[field:typelink /]\"><i class=\"icon-desktop\"></i> [field:typename /]</a></li>",757,903);
$z[4][4]=array();
$z[4][4]['typeid']="3";
$z[5]=Array("type","<li id=\"navbar-page-2\"><a href=\"[field:typelink /]\"><i class=\"icon-comments\"></i> [field:typename /]</a></li>",917,1060);
$z[5][4]=array();
$z[5][4]['typeid']="4";

?>