<li>
        <div class="arrow_box">
          <div class="ti"></div>
          <!--Èý½ÇÐÎ-->
          <div class="ci"></div>
          <!--Ô²ÐÎ-->
          <h2 class="title"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h2>
          <ul class="textinfo">
            <a href="[field:arcurl/]"><img src="[field:picname/]"></a>
            <p>[field:infos function="cn_substr(@me,240)"/]...</p>
          </ul>
          <ul class="details">
            <li class="likes"><a href="#">[field:scores/]</a></li>
            <li class="comments"><a href="#">[field:click/]</a></li>
            <li class="icon-time"><a href="#">[field:pubdate function="MyDate('Y-m-d',@me)"/]</a></li>
          </ul>
        </div>
        <!--arrow_box end--> 
      </li>