<?php
$z[0]=Array("arcurl","",62,77);
$z[1]=Array("title","",102,116);
$z[2]=Array("title","",138,152);
$z[3]=Array("pubdate","",269,316);
$z[3][4]['function']="MyDate('Y-m-d',@me)";
$z[4]=Array("writer","",323,338);
$z[5]=Array("typename","",360,377);
$z[6]=Array("arcurl","",418,433);
$z[7]=Array("picname","",519,535);
$z[8]=Array("title","",558,572);
$z[9]=Array("infos","",638,682);
$z[9][4]['function']="cn_substr(@me,180)";
$z[10]=Array("arcurl","",710,725);

?>