<p class="ptit">
              <b>
                <a href="[field:arcurl/]" target="_blank" title="[field:title/]">
                  [field:title/]
                </a>
              </b>
            </p>
            <p class="ptime">
              发布时间：[field:pubdate function="MyDate('Y-m-d',@me)"/] 作者：[field:writer/]
              分类：[field:typename/]
            </p>
            <a href="[field:arcurl/]" target="_blank" title=" li列表在网页中常见应用例举（二）">
              <img src="[field:picname/]" class="imgdow" alt=" [field:title/]">
            </a>
            <p class="pcon">
              [field:description/]...
              <a href="[field:arcurl/]" target="_blank" title=" li列表在网页中常见应用例举（二）">
                详细信息
              </a>
            </P>
            <div class="line">
            </div>