<?php
$z[0]=Array("global","",14,41);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",94,121);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",201,228);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",305,332);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",399,426);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",628,653);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel","\r\n      	<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",678,879);
$z[6][4]['type']="top";
$z[6][4]['row']="10";
$z[6][4]['currentstyle']="<li><a href='~typelink~' id='nav_current'>~typename~</a></li>";
$z[7]=Array("global","",909,936);
$z[7][4]['name']="cfg_basehost";

?>