<?php
$z[0]=Array("global","",96,121);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",522,549);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",939,966);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("arclist","\r\n          <li><span><strong>[field:global.autoindex/]</strong></span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n		",1198,1351);
$z[4]=Array("arclist","\r\n          <li style=\"margin:10px 0;\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\">[field:title/]...\r\n            <p>²é¿´ÏêÏ¸</p>\r\n            </a></li>\r\n          ",1461,1691);
$z[4][4]['row']="5";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("arclist","\r\n          <li><span>[field:typelink/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n		",1799,1953);
$z[5][4]['row']="10";
$z[5][4]['orderby']="click";

?>